name: spectHRs
channels:
  - conda-forge
  - anaconda
dependencies:
  - conda
  - conda-pack
  - gdown
  - ipython
  - ipympl
  - ipyvuetify
  - ipywidgets
  - jupyter
  - jupyterlab >=4.0.0
  - matplotlib
  - mplcursors
  - nodejs >=20,<21
  - numpy
  - pandas
  - pip
  - python >=3.10
  - pyxdf  
  - scipy
  - voila
  - voila-gridstack
  - seaborn
  - wheel
  - r-base=4.1.0
  - r-tidyverse
  - r-essentials
  - r-irkernel
  - r-rcpp
  - r-rcurl
  - r-rmarkdown
  - r-dplyr
  - r-ggplot2
  - r-tidyr
  - rstudio
  - r-plotly
  - nb_conda_kernels
  - pip:
    - pyhrv
    - easywebdav
