name: spectHR
channels:
  - conda-forge
  - anaconda
dependencies:
  - conda
  - conda-pack
  - gdown
  - ipython
  - ipympl
  - ipyvuetify
  - ipywidgets
  - jupyter
  - jupyterlab >=4.0.0
  - matplotlib
  - mplcursors
  - nodejs
  - numpy
  - pandas
  - pip
  - python >=3.10
  - pyxdf  
  - scipy
  - voila
  - voila-gridstack
  - seaborn
  - wheel
  - pip:
    - pyhrv
    - easywebdav
