name: spectHRs
channels:
  - conda-forge
  - anaconda
dependencies:
  - conda
  - conda-pack
  - ipython
  - ipympl
  - ipyvuetify
  - ipywidgets
  - jupyter
  - jupyterlab >=4.0.0
  - matplotlib
  - mplcursors
  - numpy
  - pandas
  - pip
  - python >=3.10
  - scipy
  - voila
  - voila-gridstack
  - seaborn
  - wheel
  - r-base
  - r-tidyverse
  - r-essentials
  - r-irkernel
  - r-dplyr
  - nb_conda_kernels
  - pip:
    - spectHR

