name:
  - spectHR
channels:
  - conda-forge
  - anaconda
dependencies:
  - conda
  - conda-pack
  - gdown
  - ipython
  - ipympl
  - ipyvuetify
  - ipywidgets
  - jupyter
  - jupyterlab
  - matplotlib
  - numba
  - numpy
  - pandas
  - pip
  - python
  - pyxdf  
  - scipy
  - voilà
  - voila-gridstack
  - seaborn
  - pip:
    - pyhrv
    - easywebdav