name:
  - ExperimentalSkills
channels:
  - conda-forge
  - anaconda
dependencies:
  - bokeh
  - catboost
  - conda
  - conda-pack
  - datashader
  - feather-format
  - gdown
  - html5lib
  - htmltools
  - ipython
  - ipympl
  - ipyvuetify
  - ipywidgets
  - joblib
  - jupyter
  - jupyterlab
  - lxml
  - lz4
  - matplotlib
  - networkx
  - numba
  - numpy
  - openpyxl
  - pandas
  - pillow
  - pip
  - plotly
  - pyarrow
  - python
  - pyxdf  
  - requests
  - scikit-image
  - scikit-learn
  - scipy
  - seaborn
  - snappy
  - statsmodels
  - voila
  - voila-gridstack
  - xgboost
  - xlrd
  - xlwt
  - pip:
    - pyhrv
    - easywebdav
