name: Auto-generate TOC
on: [push]

jobs:
  generate-toc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Generate TOC
        uses: technote-space/toc-generator@v4
      - name: Commit TOC changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Auto-generate TOC"
